### ISSUE TITLE
Fix Issues with Lighthouse on the CI

### ISSUE THREAD

**Issue by phil-lgr** [newrade/newrade-core#220]
## Issue

- should chrome be installed ? 
- can we use puppeteer ?
- https://github.com/GoogleChrome/lighthouse/issues/1799
- it works on the `ubuntu-latest` but not our `self-hosted` vm
- https://github.com/treosh/lighthouse-ci-action

## Config

```
    - name: Audit Deployment using Lighthouse (for PRs)
      if: ${{ env.APP_CI_DEPLOY && github.event_name == 'pull_request'}}
      uses: treosh/lighthouse-ci-action@v8
      with:
        configPath: '.github/lighthouse/lighthouserc.json'
        # temporaryPublicStorage: true
        runs: 3
        urls: |
          ${{ steps.deploy-vercel-prs.outputs.preview-url }}
```

## Todo

- [ ] add to workflows (on PR only?)
- [ ] find how to fix on vm
- [ ] maybe create user ? https://github.com/GoogleChromeLabs/lighthousebot/blob/a4bfc0857741c1cd6bde9ded967971fd27254ed6/builder/Dockerfile#L35-L40
- [ ] create separate workflow ?
- [ ] check https://perfbeacon.com/

**Comment by phil-lgr** [comment]
solved with https://github.com/foo-software/foo-api
